// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBcvMok-5Svsc2SsaluLg9dQNJSp0Sgk',
    appId: '1:208172702491:web:359210a649f4b6fc6491be',
    messagingSenderId: '208172702491',
    projectId: 'livescore-ad4fe',
    authDomain: 'livescore-ad4fe.firebaseapp.com',
    storageBucket: 'livescore-ad4fe.appspot.com',
    measurementId: 'G-WHPPHF0NPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsZJCYrnlWB137Cv9AgPsTh0g-Zu-z0o',
    appId: '1:208172702491:android:adba1f70451fb6bf6491be',
    messagingSenderId: '208172702491',
    projectId: 'livescore-ad4fe',
    storageBucket: 'livescore-ad4fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdgTB1adm1hfHY3mjoeitaYf8bXD8OKQ',
    appId: '1:208172702491:ios:ff64d7a82c98a3656491be',
    messagingSenderId: '208172702491',
    projectId: 'livescore-ad4fe',
    storageBucket: 'livescore-ad4fe.appspot.com',
    iosBundleId: 'com.example.liveScoreApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdgTB1adm1hfHY3mjoeitaYf8bXD8OKQ',
    appId: '1:208172702491:ios:ff64d7a82c98a3656491be',
    messagingSenderId: '208172702491',
    projectId: 'livescore-ad4fe',
    storageBucket: 'livescore-ad4fe.appspot.com',
    iosBundleId: 'com.example.liveScoreApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhBcvMok-5Svsc2SsaluLg9dQNJSp0Sgk',
    appId: '1:208172702491:web:21939ea4bb7305c46491be',
    messagingSenderId: '208172702491',
    projectId: 'livescore-ad4fe',
    authDomain: 'livescore-ad4fe.firebaseapp.com',
    storageBucket: 'livescore-ad4fe.appspot.com',
    measurementId: 'G-PK4VBCTWH0',
  );

}